# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LWABdwXPd3632QMbJSZi5fPBE4aucdi9
"""

app_code = '''
import streamlit as st
import pandas as pd
import numpy as np
from scipy.stats import norm
from scipy.optimize import brentq
from datetime import datetime
import matplotlib.pyplot as plt

# ── Page config ──────────────────────────────────────────────
st.set_page_config(page_title="NSE Options Scanner", layout="wide")
st.title("NSE Nifty Options Greeks Scanner")
st.markdown("Upload your NSE option chain CSV to analyse IV, Greeks and mispricing.")

# ── File upload ───────────────────────────────────────────────
uploaded_file = st.file_uploader("Upload NSE Option Chain CSV", type=["csv"])

if uploaded_file:

    # ── Load & clean ─────────────────────────────────────────
    df_raw = pd.read_csv(uploaded_file, header=1)

    def to_number(col):
        return pd.to_numeric(
            col.astype(str).str.replace(",","").str.strip(),
            errors="coerce"
        )

    calls = pd.DataFrame({
        "strike": to_number(df_raw["STRIKE"]),
        "ltp":    to_number(df_raw["LTP"]),
        "iv":     to_number(df_raw["IV"]),
        "oi":     to_number(df_raw["OI"]),
        "bid":    to_number(df_raw["BID"]),
        "ask":    to_number(df_raw["ASK"]),
        "type":   "CE"
    })

    puts = pd.DataFrame({
        "strike": to_number(df_raw["STRIKE"]),
        "ltp":    to_number(df_raw["LTP.1"]),
        "iv":     to_number(df_raw["IV.1"]),
        "oi":     to_number(df_raw["OI.1"]),
        "bid":    to_number(df_raw["BID.1"]),
        "ask":    to_number(df_raw["ASK.1"]),
        "type":   "PE"
    })

    df = pd.concat([calls, puts], ignore_index=True)
    df = df.dropna(subset=["ltp","strike"])
    df = df[df["ltp"] > 0]

    # ── Sidebar inputs ────────────────────────────────────────
    st.sidebar.header("Settings")
    spot    = st.sidebar.number_input("Nifty Spot Price", value=23622.90, step=10.0)
    expiry  = st.sidebar.date_input("Expiry Date", value=pd.to_datetime("2026-07-14"))
    r       = st.sidebar.slider("Risk-free Rate (%)", 4.0, 10.0, 6.5) / 100
    threshold = st.sidebar.slider("Mispricing Threshold (%)", 1, 20, 5)

    df["spot"]   = spot
    df["expiry"] = pd.to_datetime(expiry)
    today        = datetime.today()
    df["T"]      = df["expiry"].apply(lambda x: max((x - today).days / 365, 0))

    # ── Black-Scholes ─────────────────────────────────────────
    def black_scholes(S, K, T, r, sigma, option_type):
        if T <= 0 or sigma <= 0:
            return np.nan
        d1 = (np.log(S/K) + (r + 0.5*sigma**2)*T) / (sigma*np.sqrt(T))
        d2 = d1 - sigma*np.sqrt(T)
        if option_type == "CE":
            return round(S*norm.cdf(d1) - K*np.exp(-r*T)*norm.cdf(d2), 2)
        else:
            return round(K*np.exp(-r*T)*norm.cdf(-d2) - S*norm.cdf(-d1), 2)

    def get_bs_price(row):
        sigma = row["iv"]/100 if row["iv"] > 0 else 0.12
        return black_scholes(row["spot"], row["strike"], row["T"], r, sigma, row["type"])

    df["bs_price"] = df.apply(get_bs_price, axis=1)

    # ── Greeks ────────────────────────────────────────────────
    def calculate_greeks(S, K, T, r, sigma, option_type):
        T = max(T, 7/365)
        d1 = (np.log(S/K) + (r + 0.5*sigma**2)*T) / (sigma*np.sqrt(T))
        d2 = d1 - sigma*np.sqrt(T)
        gamma = norm.pdf(d1) / (S * sigma * np.sqrt(T))
        vega  = S * norm.pdf(d1) * np.sqrt(T) / 100
        if option_type == "CE":
            delta = norm.cdf(d1)
            theta = (-(S*norm.pdf(d1)*sigma)/(2*np.sqrt(T)) - r*K*np.exp(-r*T)*norm.cdf(d2)) / 365
        else:
            delta = norm.cdf(d1) - 1
            theta = (-(S*norm.pdf(d1)*sigma)/(2*np.sqrt(T)) + r*K*np.exp(-r*T)*norm.cdf(-d2)) / 365
        return {"delta":round(delta,4),"gamma":round(gamma,6),"theta":round(theta,2),"vega":round(vega,4)}

    greeks = df.apply(
        lambda row: calculate_greeks(
            row["spot"], row["strike"], row["T"], r,
            row["iv"]/100 if row["iv"] > 0 else 0.12,
            row["type"]
        ), axis=1
    )
    df = pd.concat([df.reset_index(drop=True), pd.DataFrame(greeks.tolist())], axis=1)

    # ── IV Solver ─────────────────────────────────────────────
    def find_iv(market_price, S, K, T, r, option_type):
        if T <= 0 or market_price <= 0:
            return np.nan
        sigma = 0.2
        for _ in range(100):
            price = black_scholes(S, K, T, r, sigma, option_type)
            if price is None or np.isnan(price):
                break
            d1 = (np.log(S/K) + (r + 0.5*sigma**2)*T) / (sigma*np.sqrt(T))
            vega = S * norm.pdf(d1) * np.sqrt(T)
            if vega < 1e-10:
                break
            diff = price - market_price
            sigma = sigma - diff/vega
            if abs(diff) < 0.001:
                return round(sigma * 100, 2)
        try:
            iv = brentq(lambda s: black_scholes(S,K,T,r,s,option_type) - market_price, 0.001, 5.0)
            return round(iv * 100, 2)
        except:
            return np.nan

    df["calc_iv"] = df.apply(
        lambda row: find_iv(row["ltp"], row["spot"], row["strike"], row["T"], r, row["type"]), axis=1
    )

    # ── Mispricing ────────────────────────────────────────────
    df["mispricing_pct"] = ((df["ltp"] - df["bs_price"]) / df["bs_price"] * 100).round(2)
    def get_signal(x):
        if x > threshold:  return "🔴 OVERPRICED"
        elif x < -threshold: return "🟢 UNDERPRICED"
        else: return "✅ FAIR"
    df["signal"] = df["mispricing_pct"].apply(get_signal)

    # ════════════════════════════════════════════════════════════
    # DASHBOARD LAYOUT
    # ════════════════════════════════════════════════════════════

    # ── Row 1: Summary metrics ────────────────────────────────
    st.subheader("Summary")
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Total Contracts",  len(df))
    col2.metric("Fairly Priced",    len(df[df["signal"]=="✅ FAIR"]))
    col3.metric("Overpriced",       len(df[df["signal"]=="🔴 OVERPRICED"]))
    col4.metric("Underpriced",      len(df[df["signal"]=="🟢 UNDERPRICED"]))

    # ── Row 2: Volatility Smile ───────────────────────────────
    st.subheader("Volatility Smile")
    ce_smile = df[(df["type"]=="CE") & df["calc_iv"].notna()].sort_values("strike")
    pe_smile = df[(df["type"]=="PE") & df["calc_iv"].notna()].sort_values("strike")

    fig, ax = plt.subplots(figsize=(12, 4))
    ax.plot(ce_smile["strike"], ce_smile["calc_iv"], marker="o", color="blue", label="Call (CE) IV")
    ax.plot(pe_smile["strike"], pe_smile["calc_iv"], marker="o", color="red",  label="Put (PE) IV")
    ax.axvline(x=spot, color="green", linestyle="--", label=f"Spot ₹{spot:,.0f}")
    ax.set_xlabel("Strike Price")
    ax.set_ylabel("Implied Volatility (%)")
    ax.set_title("Volatility Smile — Nifty Options")
    ax.legend()
    ax.grid(True, alpha=0.3)
    st.pyplot(fig)

    # ── Row 3: Greeks Table ───────────────────────────────────
    st.subheader("Greeks Table")
    option_filter = st.radio("Show:", ["Both", "CE only", "PE only"], horizontal=True)
    if option_filter == "CE only":
        display_df = df[df["type"] == "CE"]
    elif option_filter == "PE only":
        display_df = df[df["type"] == "PE"]
    else:
        display_df = df

    st.dataframe(
        display_df[["strike","type","ltp","bs_price","delta","gamma","theta","vega","signal"]]
        .sort_values("strike")
        .reset_index(drop=True),
        use_container_width=True
    )

    # ── Row 4: Mispricing Scanner ─────────────────────────────
    st.subheader("Mispricing Scanner")
    mispriced = df[df["signal"] != "✅ FAIR"].sort_values("mispricing_pct", ascending=False)

    if len(mispriced) == 0:
        st.success("No mispriced contracts found at current threshold.")
    else:
        st.dataframe(
            mispriced[["strike","type","ltp","bs_price","mispricing_pct","signal"]]
            .reset_index(drop=True),
            use_container_width=True
        )
'''

# Write app.py to disk
with open('app.py', 'w') as f:
    f.write(app_code)

print("app.py created successfully!")